config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  #authenticated :user do
    resources :ratings
    resources :paymentmethods
    resources :ordersdetails
    resources :orders
    resources :genres
    resources :employees
    resources :customers
    resources :books
    resources :authors
  #end

  # get 'home/index'
  get 'home/about'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :paymentmethod, :optional => true
  belongs_to :employee
  belongs_to :customer
end

app/models/ordersdetail.rb
class Ordersdetail < ApplicationRecord
  belongs_to :order
  belongs_to :book
end

app/models/paymentmethod.rb
class Paymentmethod < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/ordersdetails_controller.rb
class OrdersdetailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ordersdetail, only: %i[ show edit update destroy ]

  # GET /ordersdetails or /ordersdetails.json
  def index
    return
    @ordersdetails = Ordersdetail.all
  end

  # GET /ordersdetails/1 or /ordersdetails/1.json
  def show
    return
  end

  # GET /ordersdetails/new
  def new
    return
    @ordersdetail = Ordersdetail.new
  end

  # GET /ordersdetails/1/edit
  def edit
    return
  end

  # POST /ordersdetails or /ordersdetails.json
  def create
    return
    @ordersdetail = Ordersdetail.new(ordersdetail_params)

    respond_to do |format|
      if @ordersdetail.save
        format.html { redirect_to ordersdetail_url(@ordersdetail), notice: "Ordersdetail was successfully created." }
        format.json { render :show, status: :created, location: @ordersdetail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ordersdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordersdetails/1 or /ordersdetails/1.json
  def update
    return
    respond_to do |format|
      if @ordersdetail.update(ordersdetail_params)
        format.html { redirect_to ordersdetail_url(@ordersdetail), notice: "Ordersdetail was successfully updated." }
        format.json { render :show, status: :ok, location: @ordersdetail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ordersdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordersdetails/1 or /ordersdetails/1.json
  def destroy
    return
    @ordersdetail.destroy!

    respond_to do |format|
      format.html { redirect_to ordersdetails_url, notice: "Ordersdetail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordersdetail
      @ordersdetail = Ordersdetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ordersdetail_params
      params.require(:ordersdetail).permit(:order_id, :book_id)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ordersdetails_helper.rb
module OrdersdetailsHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ordersdetails/_form.html.erb
<%= form_with(model: ordersdetail) do |form| %>
  <% if ordersdetail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ordersdetail.errors.count, "error") %> prohibited this ordersdetail from being saved:</h2>

      <ul>
        <% ordersdetail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_id, style: "display: block" %>
    <%= form.text_field :order_id %>
  </div>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.text_field :book_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ordersdetails/_ordersdetail.html.erb
<div id="<%= dom_id ordersdetail %>">
  <p>
    <strong>Order:</strong>
    <%= ordersdetail.order_id %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= ordersdetail.book_id %>
  </p>

</div>

app/views/ordersdetails/edit.html.erb
<h1>Editing Orders Details</h1>

<%= render "form", ordersdetail: @ordersdetail %>

<br>

<div>
  <%= link_to "Show this Orders Details", @ordersdetail %> |
  <%= link_to "Back to Orders Details", ordersdetails_path %>
</div>

app/views/ordersdetails/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders Details</h1>

<div id="ordersdetails">
  <% @ordersdetails.each do |ordersdetail| %>
    <%= render ordersdetail %>
    <p>
      <%= link_to "Show this Orders Details", ordersdetail %>
    </p>
  <% end %>
</div>

<%= link_to "New Orders Details", new_ordersdetail_path %>

app/views/ordersdetails/new.html.erb
<h1>New Orders Details</h1>

<%= render "form", ordersdetail: @ordersdetail %>

<br>

<div>
  <%= link_to "Back to Orders Details", ordersdetails_path %>
</div>

app/views/ordersdetails/show.html.erb
<%= render @ordersdetail %>

<div>
  <%= link_to "Edit this Orders Details", edit_ordersdetail_path(@ordersdetail) %> |
  <%= link_to "Back to Orders Details", ordersdetails_path %>

  <%= button_to "Destroy this Orders Details", @ordersdetail, method: :delete %>
</div>