config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  #authenticated :user do
    resources :ratings
    resources :paymentmethods
    resources :ordersdetails
    resources :orders
    resources :genres
    resources :employees
    resources :customers
    resources :books
    resources :authors
  #end

  # get 'home/index'
  get 'home/about'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :paymentmethod, :optional => true
  belongs_to :employee
  belongs_to :customer
end

app/models/ordersdetail.rb
class Ordersdetail < ApplicationRecord
  belongs_to :order
  belongs_to :book
end

app/models/paymentmethod.rb
class Paymentmethod < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def about

  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag('bookstore_image.png', alt: 'BookstoreImage', class: 'img-fluid', style: 'max-width: 100px; height: auto;') %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Authors', authors_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Books', books_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Genres', genres_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Ratings', ratings_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Payment Methods', paymentmethods_path, class: "nav-link active" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Customers', customers_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Employees', employees_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Orders', orders_path, class: "nav-link active" %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdown">
            <% if user_signed_in? %>
              <li class="dropdown-item">
                <%= link_to 'Edit Account', edit_user_registration_path, class: "nav-link active" %>
              </li>
              <li class="dropdown-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link active" %>
              </li>
            <% else %>
              <li class="dropdown-item">
                <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link active" %>
              </li>
              <li class="dropdown-item">
                <%= link_to 'Sign In', new_user_session_path, class: "nav-link active" %>
              </li>
            <% end %>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About this Website</h1>

This is a Demo Website for a bookshop. Currently, it is only usable with Administrator privileges.

<br>

The purpose of this website is to put emphasis on security!

app/views/home/index.html.erb
<h1>Hello!</h1>

<br>

<h2>Welcome to my Bookshop Website!</h2>