config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  #authenticated :user do
    resources :ratings
    resources :paymentmethods
    resources :ordersdetails
    resources :orders
    resources :genres
    resources :employees
    resources :customers
    resources :books
    resources :authors
  #end

  # get 'home/index'
  get 'home/about'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :paymentmethod, :optional => true
  belongs_to :employee
  belongs_to :customer
end

app/models/ordersdetail.rb
class Ordersdetail < ApplicationRecord
  belongs_to :order
  belongs_to :book
end

app/models/paymentmethod.rb
class Paymentmethod < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/paymentmethods_controller.rb
class PaymentmethodsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_paymentmethod, only: %i[ show edit update destroy ]

  # GET /paymentmethods or /paymentmethods.json
  def index
    @paymentmethods = Paymentmethod.order(:name)
  end

  # GET /paymentmethods/1 or /paymentmethods/1.json
  def show
  end

  # GET /paymentmethods/new
  def new
    @paymentmethod = Paymentmethod.new
  end

  # GET /paymentmethods/1/edit
  def edit
  end

  # POST /paymentmethods or /paymentmethods.json
  def create
    @paymentmethod = Paymentmethod.new(paymentmethod_params)

    respond_to do |format|
      if @paymentmethod.save
        format.html { redirect_to paymentmethod_url(@paymentmethod), notice: "Paymentmethod was successfully created." }
        format.json { render :show, status: :created, location: @paymentmethod }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paymentmethod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paymentmethods/1 or /paymentmethods/1.json
  def update
    respond_to do |format|
      if @paymentmethod.update(paymentmethod_params)
        format.html { redirect_to paymentmethod_url(@paymentmethod), notice: "Paymentmethod was successfully updated." }
        format.json { render :show, status: :ok, location: @paymentmethod }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paymentmethod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paymentmethods/1 or /paymentmethods/1.json
  def destroy
    @paymentmethod.destroy!

    respond_to do |format|
      format.html { redirect_to paymentmethods_url, notice: "Paymentmethod was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paymentmethod
      @paymentmethod = Paymentmethod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paymentmethod_params
      params.require(:paymentmethod).permit(:name)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/paymentmethods_helper.rb
module PaymentmethodsHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/paymentmethods/_form.html.erb
<%= form_with(model: paymentmethod) do |form| %>
  <% if paymentmethod.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(paymentmethod.errors.count, "error") %> prohibited this paymentmethod from being saved:</h2>

      <ul>
        <% paymentmethod.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control", style: "width: 200px;"  %>
  </div>

  <br>
  <div class="form-group">
    <%= form.submit class: "btn btn-success"%>
  </div>
<% end %>

app/views/paymentmethods/_paymentmethod.html.erb
<div id="<%= dom_id paymentmethod %>">
  <p>
    <strong>Name:</strong>
    <%= paymentmethod.name %>
  </p>

</div>

app/views/paymentmethods/edit.html.erb
<h1>Edit Payment Method</h1>

<%= render "form", paymentmethod: @paymentmethod %>

<br>

<div>
  <%= link_to "Back", paymentmethods_path, class: "btn btn-info btn-sm", style: "color: white"%>
</div>

app/views/paymentmethods/index.html.erb
<div class="container">
  <h1 class="text-center">List of Payment Methods</h1>

  <table class="table table-striped">
    <thead>
    <tr>
      <th style="font-size: 20px">Payment Method Name</th>
      <th></th>
    </tr>
    </thead>
    <tbody class="table-group-divider">
    <% @paymentmethods.each do |paymentmethod| %>
      <tr>
        <td><%= paymentmethod.name %></td>
        <td>
          <%= link_to "Show", paymentmethod, class: "btn btn-primary" %>
        </td>
        <% if user_signed_in? %>
          <td>
            <%= link_to "Edit", edit_paymentmethod_path(paymentmethod), class: "btn btn-warning", style: "color: white;"%>
          </td>
          <td>
            <%= button_to "Destroy", paymentmethod, method: :delete, class: "btn btn-danger"%>
          </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
  <% if user_signed_in? %>
    <%= link_to "Create New Payment Method", new_paymentmethod_path, class: "btn btn-success" %>
  <% end %>
</div>
<br><br>

app/views/paymentmethods/new.html.erb
<h1>New Payment Method</h1>

<%= render "form", paymentmethod: @paymentmethod %>

<br>

<div>
  <%= link_to "Back", paymentmethods_path, class: "btn btn-info btn-sm", style: "color: white"%>
</div>

app/views/paymentmethods/show.html.erb
<%= render @paymentmethod %>

<div>
  <%= link_to "Back", paymentmethods_path, class: "btn btn-info btn-sm", style: "color: white;"%>
</div>