config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  #authenticated :user do
    resources :ratings
    resources :paymentmethods
    resources :ordersdetails
    resources :orders
    resources :genres
    resources :employees
    resources :customers
    resources :books
    resources :authors
  #end

  # get 'home/index'
  get 'home/about'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :paymentmethod, :optional => true
  belongs_to :employee
  belongs_to :customer
end

app/models/ordersdetail.rb
class Ordersdetail < ApplicationRecord
  belongs_to :order
  belongs_to :book
end

app/models/paymentmethod.rb
class Paymentmethod < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_rating, only: %i[ show edit update destroy ]

  # GET /ratings or /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1 or /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings or /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to rating_url(@rating), notice: "Rating was successfully created." }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1 or /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to rating_url(@rating), notice: "Rating was successfully updated." }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1 or /ratings/1.json
  def destroy
    @rating.destroy!

    respond_to do |format|
      format.html { redirect_to ratings_url, notice: "Rating was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rating_params
      params.require(:rating).permit(:book_id, :comments, :number_of_stars)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_with(model: rating) do |form| %>
  <% if rating.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
        <% rating.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :book_id, "Book", style: "display: block" %>
    <%= form.select :book_id, Book.all.map { |book| [book.title, book.id] }, class: "form-control" %>
  </div>

  <div>
    <%= form.label :comments, style: "display: block" %>
    <%= form.text_area :comments, class: "form-control", style: "width: 200px;" %>
  </div>

  <div>
    <%= form.label :number_of_stars, style: "display: block" %>
    <%= form.text_field :number_of_stars, class: "form-control", style: "width: 200px;" %>
  </div>

  <br>
  <div class="form-group">
    <%= form.submit class: "btn btn-success"%>
  </div>
<% end %>

app/views/ratings/_rating.html.erb
<div id="<%= dom_id rating %>">
</div>

app/views/ratings/edit.html.erb
<h1>Edit Rating</h1>

<%= render "form", rating: @rating %>

<br>

<div>
  <%= link_to "Back", ratings_path, class: "btn btn-info btn-sm", style: "color: white"%>
</div>

app/views/ratings/index.html.erb
<div class="container">
  <h1 class="text-center">List of Ratings</h1>

  <table class="table table-striped">
    <thead>
    <tr>
      <th style="font-size: 20px">Rating Id</th>
      <th></th>
    </tr>
    </thead>
    <tbody class="table-group-divider">
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.review_id %></td>
        <td>
          <%= link_to "Show", rating, class: "btn btn-primary" %>
        </td>
        <% if user_signed_in? %>
          <td>
            <%= link_to "Edit", edit_rating_path(rating), class: "btn btn-warning", style: "color: white;"%>
          </td>
          <td>
            <%= button_to "Destroy", rating, method: :delete, class: "btn btn-danger"%>
          </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
  <% if user_signed_in? %>
    <%= link_to "Create New Rating", new_rating_path, class: "btn btn-success" %>
  <% end %>
</div>
<br><br>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render "form", rating: @rating %>

<br>

<div>
  <%= link_to "Back", ratings_path, class: "btn btn-info btn-sm", style: "color: white"%>
</div>

app/views/ratings/show.html.erb
<p><strong>Book: </strong><%= Book.find(@rating.book_id).title %></p>
<p><strong>Comments: </strong><%= @rating.comments %></p>
<p><strong>Number of Stars: </strong><%= @rating.number_of_stars %></p>

<div>
  <%= link_to "Back", ratings_path, class: "btn btn-info btn-sm", style: "color: white;"%>
</div>